### ISSUE TITLE
GET /meeting/summary responding with 401 Unauthorized

### ISSUE THREAD

**Issue by timbuncee** [OfficeDev/microsoft-teams-sample-meetings-token#2]
I'm in process of setting up Token App for meetings and ran into some issues regarding getting access token for routes.

The bot SSO was set up following the auth method [here](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso).

After fully setting up the bot and updating the appsetting.json and manifest.json accordingly, the tab was responding with 401 on /meeting/summary request therefore not giving me the expected flow to test the app.

Actual Tab view
![image](https://user-images.githubusercontent.com/38078854/94815515-9c90a600-03c8-11eb-9470-6e192f6b18f1.png)

Inspector network response
![image](https://user-images.githubusercontent.com/38078854/94815520-a0242d00-03c8-11eb-8545-1367b06964a4.png)

dotnet error log
![image](https://user-images.githubusercontent.com/38078854/94815527-a31f1d80-03c8-11eb-9e46-6b3fb70f8d21.png)

Any point of direction or help to resolve this will greatly appreciate and will be happy to provide any more information that can help debug this issue.

**Comment by koushik-shetty** [comment]
Hi @timbuncee,

Thank you for trying out the sample. 

We have noted the issue, and will be releasing a fix very soon. 

In the meantime, to solve this issue please set the `ApplicationIdUri` in the appsettings.json to the same value as `MicrosoftAppId`. This is because the audience is set to the MicrosoftAppId(client id) in the token claims.

**Comment by timbuncee** [comment]
Thank you! I got it working. Looking forward to more updates.
![image](https://user-images.githubusercontent.com/38078854/94821610-c13c4c00-03cf-11eb-9544-ed70a500a762.png)
