### ISSUE TITLE
The sidepanel app is not able to be displayed on in-meeting panel. 

### ISSUE THREAD

**Issue by skeletonKim** [OfficeDev/microsoft-teams-sample-meetings-token#6]
Without any changes except ngrok endpoint, I have tried to access my SidePanel App in Teams, currently for testing by Devpreview manifest.json. 
This is for a feasibility check of displaying the app during the meeting. It was working well till last week. but suddenly it is not able to display anymore. I have not changed any configurations from last which was working well. 

I am attaching my manifest.json after removing confidential information. As a mention for referring, I have already set on Teams Admin, Activate Teams app > Setup policies > Upload custom apps. ( https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?tabs=json )

And Turned on Developer Preview of User Setting.

![image](https://user-images.githubusercontent.com/70251740/98883766-19d42e00-24d2-11eb-9035-3cbdd0cfa2c4.png)

And Delete Teams cache data in %AppData%Microsoft / Reinstall App after uninstalling. - Not solved

The Same App is visible on ChannelTab, but not visible on the unified bar (u-bar) of in-meeting panel.

![image](https://user-images.githubusercontent.com/70251740/98621685-2aa66780-234b-11eb-9c5d-9eaab3acd6cd.png)

This image is the screenshot, succeeded last time.

![image](https://user-images.githubusercontent.com/70251740/98498109-4cd7b100-2289-11eb-8907-8353e9ce93e2.png)

1) Does the manifest loader in teams have any mechanism of internal cache? could you tell me how to initialize all cache data related side panel app?
2) In terms of the settings for activating Development preview, It seems to not have any omitted part. If it is not, Could you tell me any setting should be checked?
3) Is there any changes to the loading side panel in-meeting app?  

# manifest.json
```json
{
   "$schema": "https://raw.githubusercontent.com/OfficeDev/microsoft-teams-app-schema/preview/DevPreview/MicrosoftTeams.schema.json",
   "manifestVersion": "devPreview",
   "version": "1.0.0",
   "id": "aa32a7c1-45d5-455b-8752-882c58aa773c",
   "packageName": "demo.contoso.teams.extension",
   "developer": {
      "name": "skeletonKim",
      "websiteUrl": "https://45f3bbb9528c.ngrok.io",
      "privacyUrl": "https://45f3bbb9528c.ngrok.io/privacy",
      "termsOfUseUrl": "https://45f3bbb9528c.ngrok.io/termsofuse"
   },
   "icons": {
      "color": "color.png",
      "outline": "outline.png"
   },
   "name": {
      "short": "Demo App",
      "full": "Demo App"
   },
   "description": {
      "short": "Short description for Demo App.",
      "full": "Full description of Demo App for Microsoft Teams."
   },
   "accentColor": "#FFFFFF",
   "bots": [],
   "composeExtensions": [],
   "configurableTabs": [
      {
        "configurationUrl": "https://45f3bbb9528c.ngrok.io/config",
        "canUpdateConfiguration": true,
        "scopes": [
          "team",
          "groupchat"
        ],
        "context":[
          "channelTab",
          "privateChatTab",
          "meetingChatTab",
          "meetingDetailsTab",
          "meetingSidePanel"
       ]
     }
   ],
   "permissions": [
      "identity",
      "messageTeamMembers"
   ],
   "devicePermissions": [
      "media",
      "geolocation",
      "notifications",
      "midi",
      "openExternal"
   ],
   "validDomains": [ 
      "*.ngrok.io"
   ]
}
```

**Comment by skeletonKim** [comment]
Obviously, This is a Teams bug, regardless of the machine and OS, it is not able to activate meetingSidePanel app.

I have tested again using several versions of Windows 10 OS on Azure after activating Developer Preview option of client-side and Admin setting of developer tenant. But it cannot activate In-meeting side panel app. I assumed at the beginning, It is caused by a certain environment. But by test, this is not caused by OS and Machine, I can finalize the conclusion that it is caused by Teams Defect.

Your team would need to go through the specific reason for this issue. If you need further, please escalate this issue to the development team.

I did the followings as you instructed, I have already known the below settings. 
 The tenant admin: Activate Teams app > Setup policies > Upload custom apps.
 The teams client : User Profile > About > Development Preview > Switch..

**Comment by koushik-shetty** [comment]
> 
> 
> Without any changes except ngrok endpoint, I have tried to access my SidePanel App in Teams, currently for testing by Devpreview manifest.json.
> This is for a feasibility check of displaying the app during the meeting. It was working well till last week. but suddenly it is not able to display anymore. I have not changed any configurations from last which was working well.
> 
> I am attaching my manifest.json after removing confidential information. As a mention for referring, I have already set on Teams Admin, Activate Teams app > Setup policies > Upload custom apps. ( https://docs.microsoft.com/en-us/microsoftteams/platform/apps-in-teams-meetings/create-apps-for-teams-meetings?tabs=json )
> 
> And Turned on Developer Preview of User Setting.
> 
> ![image](https://user-images.githubusercontent.com/70251740/98883766-19d42e00-24d2-11eb-9035-3cbdd0cfa2c4.png)
> 
> And Delete Teams cache data in %AppData%Microsoft / Reinstall App after uninstalling. - Not solved
> 
> The Same App is visible on ChannelTab, but not visible on the unified bar (u-bar) of in-meeting panel.
> 
> ![image](https://user-images.githubusercontent.com/70251740/98621685-2aa66780-234b-11eb-9c5d-9eaab3acd6cd.png)
> 
> This image is the screenshot, succeeded last time.
> 
> ![image](https://user-images.githubusercontent.com/70251740/98498109-4cd7b100-2289-11eb-8907-8353e9ce93e2.png)
> 
>     1. Does the manifest loader in teams have any mechanism of internal cache? could you tell me how to initialize all cache data related side panel app?
> 
>     2. In terms of the settings for activating Development preview, It seems to not have any omitted part. If it is not, Could you tell me any setting should be checked?
> 
>     3. Is there any changes to the loading side panel in-meeting app?
> 
> 
> # manifest.json
> 
> ```json
> {
>    "$schema": "https://raw.githubusercontent.com/OfficeDev/microsoft-teams-app-schema/preview/DevPreview/MicrosoftTeams.schema.json",
>    "manifestVersion": "devPreview",
>    "version": "1.0.0",
>    "id": "aa32a7c1-45d5-455b-8752-882c58aa773c",
>    "packageName": "demo.contoso.teams.extension",
>    "developer": {
>       "name": "skeletonKim",
>       "websiteUrl": "https://45f3bbb9528c.ngrok.io",
>       "privacyUrl": "https://45f3bbb9528c.ngrok.io/privacy",
>       "termsOfUseUrl": "https://45f3bbb9528c.ngrok.io/termsofuse"
>    },
>    "icons": {
>       "color": "color.png",
>       "outline": "outline.png"
>    },
>    "name": {
>       "short": "Demo App",
>       "full": "Demo App"
>    },
>    "description": {
>       "short": "Short description for Demo App.",
>       "full": "Full description of Demo App for Microsoft Teams."
>    },
>    "accentColor": "#FFFFFF",
>    "bots": [],
>    "composeExtensions": [],
>    "configurableTabs": [
>       {
>         "configurationUrl": "https://45f3bbb9528c.ngrok.io/config",
>         "canUpdateConfiguration": true,
>         "scopes": [
>           "team",
>           "groupchat"
>         ],
>         "context":[
>           "channelTab",
>           "privateChatTab",
>           "meetingChatTab",
>           "meetingDetailsTab",
>           "meetingSidePanel"
>        ]
>      }
>    ],
>    "permissions": [
>       "identity",
>       "messageTeamMembers"
>    ],
>    "devicePermissions": [
>       "media",
>       "geolocation",
>       "notifications",
>       "midi",
>       "openExternal"
>    ],
>    "validDomains": [ 
>       "*.ngrok.io"
>    ]
> }
> ```

Hi @skeletonKim ,

I see that your manifest is missing [webApplicationInfo](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso#2-update-your-microsoft-teams-application-manifest) key. Can you add that?

Also, this is available only in desktop client as of now, so please make sure you test it there

**Comment by skeletonKim** [comment]
Hi @koushik-shetty,
> 
> I see that your manifest is missing [webApplicationInfo](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso#2-update-your-microsoft-teams-application-manifest) key. Can you add that?
> 
> Also, this is available only in desktop client as of now, so please make sure you test it there

Thank you for your response. but I have a question about your answer. Is the webApplicationInfo necessary?

Written on [here](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema-dev-preview), this is an optional property. And before I got a problem, attached a worked screenshot, It worked without this property. 

I have already known this functionality only working on a desktop application. If you need any log or meeting for further investigation. please let me know.

**Comment by skeletonKim** [comment]
Hi @koushik-shetty 

I added this setting in the manifest.json with fixing the code and AD app registration.

   "webApplicationInfo": {
      "id": "6ccb1a5c-3419-xxxx-xxxx-xxxxxxxxxxxx",
      "resource": "api://fc0914711e60.ngrok.io/6ccb1a5c-3419-xxxx-xxxx-xxxxxxxxxxxx"
   }

AD settings and your guidance about webApplicationInfo key, It was not working at all. 
I can see a similar screen and get the token from AD. But the button still is not visible on the meeting side-panel.

![image](https://user-images.githubusercontent.com/70251740/99783095-500e4f00-2b5d-11eb-89bf-4783ee9ebd68.png)

Would you share any progress in solving this issue?.

**Comment by skeletonKim** [comment]
I found how to activate by myself.
